
---
# Namespace for agent tests
apiVersion: v1
kind: Namespace
metadata:
  name: test-tool-servers
---

apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolServer
metadata:
  labels:
    app.kubernetes.io/name: agent-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-http-toolserver
  namespace: test-tool-servers
spec:
  protocol: mcp
  transportType: http
  image: mcp/context7:latest
  port: 8080
  path: /mcp
  replicas: 1
  env:
    - name: LOGLEVEL
      value: INFO
