apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: OperatorConfiguration
metadata:
  name: default
spec:
  agentTemplateImages:
    # Customize the default template image for Google ADK framework agents
    # This will be used when an Agent resource does not specify a custom image
    googleAdk: "ghcr.io/agentic-layer/agent-template-adk:0.6.1"
