# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/runtime.agentic-layer.ai_agentgateways.yaml
- bases/runtime.agentic-layer.ai_agentgatewayclasses.yaml
- bases/runtime.agentic-layer.ai_agenticworkforces.yaml
- bases/runtime.agentic-layer.ai_agents.yaml
- bases/runtime.agentic-layer.ai_agentruntimeconfigurations.yaml
- bases/runtime.agentic-layer.ai_aigateways.yaml
- bases/runtime.agentic-layer.ai_aigatewayclasses.yaml
- bases/runtime.agentic-layer.ai_toolgatewayclasses.yaml
- bases/runtime.agentic-layer.ai_toolgateways.yaml
- bases/runtime.agentic-layer.ai_toolservers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
